"""
Grader Agent for Knowledge Sub-Graph

This module exports the Grader node, which performs Quality Control (QC)
on draft answers generated by the Investigator.
"""
from .node import run_grader
from .prompt import GRADER_PROMPT
from .schema import Grade

__all__ = ["run_grader", "GRADER_PROMPT", "Grade"]
